# Generated by Django 2.2.7 on 2019-11-05 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('api', '0034_post_ispublic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MygUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.ImageField(blank=True, default='/media/profile/e2.png', upload_to='profile')),
                ('sex', models.BooleanField(default=True)),
                ('dad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DAD', to='api.MygUser')),
                ('mom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MOM', to='api.MygUser')),
            ],
        ),
        migrations.CreateModel(
            name='Sibling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sibling1', models.ForeignKey(on_delete=False, related_name='User', to='api.MygUser')),
                ('sibling2', models.ForeignKey(on_delete=False, related_name='Sibling', to='api.MygUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='action',
            name='post',
        ),
        migrations.RemoveField(
            model_name='action',
            name='user',
        ),
        migrations.RemoveField(
            model_name='advertsettings',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='memecontent',
            name='post',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.RemoveField(
            model_name='mimeuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Mods',
        ),
        migrations.RemoveField(
            model_name='personalscoringprofile',
            name='label',
        ),
        migrations.RemoveField(
            model_name='personalscoringprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postlabelling',
            name='label',
        ),
        migrations.RemoveField(
            model_name='postlabelling',
            name='post',
        ),
        migrations.RemoveField(
            model_name='template',
            name='user',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='content_post',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='AdvertSettings',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='MemeContent',
        ),
        migrations.DeleteModel(
            name='MimeUser',
        ),
        migrations.DeleteModel(
            name='PersonalScoringProfile',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostLabelling',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.DeleteModel(
            name='TimeLine',
        ),
    ]
